package com.class37;

public class UncheckedException {
	public static void main(String[] args) {
		System.out.println("Beginning of your code");
		int a = 20;
		int b = 0;
		
		try {
			System.out.println("I am a code inside try block");
			System.out.println(a/b);
			System.out.println("Continuation of the code inside try block");
		}
		catch(ArithmeticException e){ //ArithmeticException e = new ArithmeticException();
			System.out.println("I am code inside catch block");
//			e.printStackTrace();//print the exception message as generated by JVM
//								//details of where in the code exceptions occurred, name of the
//								//exception and detailed message
//			System.out.println(e);//can also print the exception
			System.out.println(e.getMessage()); //just the message no detailed explanation
		}
		System.out.println("End of your code");
	}
}
